### ISSUE TITLE
add "node" to Node-RED 

### ISSUE THREAD

**Issue by twocolors** [ttimpe/homebridge-laundrify#1]
Hi, could you add support for the Node-RED too?

**Comment by ttimpe** [comment]
Is there a reason this issue was closed?

**Comment by ttimpe** [comment]
A Node-RED Plugin could be built using the existing code of this Homebridge plugin. As I personally don‘t use Node-RED however, I don‘t see the benefit.

If I have time and this project gets to a stable state, it could be broken up into two packages: 
- Laundrify control
- Actual Homebridge Plugin

A Node-RED Plugin could then built on top of the first one.
